### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [Dijana181/Python-Capstone-Project#1]
Valid Python Code (4/4)
Code included runs without any errors.

Implementation of Project Requirements (4/4)
Code produces the suite of functions and classes required of it and calls them in an appropriate order.

Software Architecture (4/4)
Code is separated into distinct classes and functions each which are invoked for their own purposes. 

Uses Python Language Features (4/4)
Code uses language features appropriately. If a task can be solved with a Python language feature, it is.

Excellent job! One small suggestion I have is to use "return" instead of "print" in certain functions so your console doesn't bring a None value. Otherwise, everything looks great.

**Comment by Dijana181** [comment]
Thanks for the feedback navierula!
